name: ci
on:
  push:
  pull_request:
jobs:
  test-jvm:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.1
        with:
          lein: latest
      - name: Run unit tests
        run: lein test
